spring.application.name=payment-service
server.port=8085

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=payments_db

razorpay.key.id=rzp_test_T7neP0IIy6kOYT
razorpay.key.secret=9IJg5GH4iCrngn3hpN8Yybuz

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true